<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>Materiali</AssemblyName>
    <GpcLibraries>GPCModel;GPCUtilities</GpcLibraries>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../X.Calculations/X.Calculations.csproj" /></ItemGroup>
  <ItemGroup>
    <Resource Include="Assets/*.png" />
  </ItemGroup>
</Project>
