<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>Materiali</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../X.Calculations/X.Calculations.csproj" /></ItemGroup>
  <ItemGroup>
    <Reference Include="GPCModel"><HintPath>../lib/Checker/GPCModel.dll</HintPath></Reference>
    <Reference Include="GPCUtilities"><HintPath>../lib/Checker/GPCUtilities.dll</HintPath></Reference>
    <Resource Include="Assets/*.png" />
  </ItemGroup>
</Project>
