<#
Writes lib\Checker\manifest.props from lib\Checker\manifest.json: one GpcLibraryFile item per DLL with its SHA-256
and assembly version. Directory.Build.targets imports it to verify the snapshot at every build.

  powershell -NoProfile -ExecutionPolicy Bypass -File tools\libs\Write-ManifestProps.ps1 [-LibDir <folder>]

The script refuses to write the file if a DLL on disk does not match the manifest.
#>
param([string] $LibDir)
$ErrorActionPreference = 'Stop'
if (-not $LibDir) { $LibDir = Join-Path $PSScriptRoot '..\..\lib\Checker' }
$LibDir = [IO.Path]::GetFullPath($LibDir)
$manifest = Get-Content -LiteralPath (Join-Path $LibDir 'manifest.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('<Project>')
$lines.Add('  <!-- Generated by tools\libs\Write-ManifestProps.ps1 from manifest.json: do not edit by hand. -->')
$lines.Add('  <ItemGroup>')
foreach ($a in ($manifest.assemblies | Sort-Object file)) {
    $path = Join-Path $LibDir $a.file
    if (-not (Test-Path -LiteralPath $path)) { throw "DLL assente: $path" }
    $actual = (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash
    if ($actual -ne $a.sha256.ToUpperInvariant()) { throw "SHA-256 di $($a.file) diverso dal manifest: $actual" }
    $lines.Add(('    <GpcLibraryFile Include="$(MSBuildThisFileDirectory){0}" Sha256="{1}" AssemblyVersion="{2}" />' -f $a.file, $a.sha256.ToUpperInvariant(), $a.assemblyVersion))
}
$lines.Add('  </ItemGroup>')
$lines.Add('</Project>')
$target = Join-Path $LibDir 'manifest.props'
[IO.File]::WriteAllText($target, (($lines -join "`r`n") + "`r`n"), (New-Object Text.UTF8Encoding($false)))
Write-Output "Scritto $target ($(@($manifest.assemblies).Count) DLL)"
