<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="../../../X.Core/X.Core.csproj"/><ProjectReference Include="../../../X.Materiali/X.Materiali.csproj"/><Reference Include="../../../lib/Checker/*.dll" /></ItemGroup></Project>
