<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../X.Desktop/X.Desktop.csproj" /><Reference Include="GPCChecker.Geotechnics"><HintPath>../../../lib/Checker/GPCChecker.Geotechnics.dll</HintPath></Reference></ItemGroup>
</Project>
