"""Programma di sviluppo: contenuti verificabili, stime residue e fonti."""
from pathlib import Path
import json, math, datetime, openpyxl
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'supporto/artefatti/programma-anthea-20261006'
phases=[
('P00','Consolidamento e baseline','M00','Priorità, casi pilota e versione di riferimento concordati.'),
('P01','Nucleo comune e interoperabilità','M01','Contratti dati e calcoli indipendenti dalla UI verificati.'),
('P02','Completamento calcestruzzo','M02','Sezioni generiche, punzonamento e inghisaggi nel perimetro concordato.'),
('P03','Completamento geotecnica','M03','Fondazioni e cedimenti con esempi controllati. Primo rilascio esteso.'),
('P04','Azioni e combinazioni','M04','Azioni esportabili e combinazioni coerenti e tracciabili.'),
('P05','Acciaio e connessioni','M05','Modulo acciaio autonomo e prima famiglia di collegamenti.'),
('P06','Misto e ponti','M06','Flusso ponte-sezione e predalles con fasi di costruzione.'),
('P07','Calcestruzzo precompresso','M07','CAP nelle fasi concordate, con perdite e controlli dedicati.'),
('P08','Rilascio integrato','M08','Versione integrata accettata su progetti pilota.'),
('B01','Nucleo openBIM','MB1','IFC, identificativi, requisiti dati ed esiti associati agli oggetti.'),
('B02','Connettore Revit','MB2','Pilota Revit con import e restituzione controllata.'),
('B03','Connettore Tekla','MB3','Pilota Tekla con import e restituzione controllata.'),
('B04','Coordinamento BIM e consegna','MB4','Revisioni, conflitti e feedback BIM provati nei due ambienti.')]
tasks=[]
def task(id,phase,area,title,scope,status,priority,deps,lo,base,hi,accept,test,source):
    tasks.append(dict(id=id,phase=phase,area=area,title=title,scope=scope,status=status,priority=priority,deps=deps,lo=lo,base=base,hi=hi,accept=accept,test=test,source=source))
task('T01','P00','Qualità','Inventario e requisiti','Congelare baseline DLL, copertura effettiva, esclusioni e priorità della bozza. Scegliere tre progetti pilota.','Estensione','P0','—',2,3,4,'Matrice bozza → funzioni → attività, senza voci perse.','TST01','Bozza; ModuleCatalog; guide Rev30')
task('T02','P00','Qualità','Regressioni e prestazioni','Rieseguire suite esistenti, casi tensionali, ottimizzazione e archivi. Misurare tempi mediani/p95, memoria e cancellazione.','Estensione','P0','T01',3,5,7,'Baseline ripetibile su macchina e file fissati; difetti classificati.','TST01; TST02','Suite esistenti; diagnosi tensioni; ricerca armature')
task('T03','P00','Qualità','Correzioni prioritarie e feedback','Riprodurre i difetti dei casi pilota, risolvere quelli bloccanti e consolidare i flussi UI/report.','Estensione','P0','T02',3,4,7,'Nessun difetto bloccante noto nel perimetro del rilascio.','TST03; TST04','Feedback utente; guide pratiche')
task('T04','P01','Piattaforma','Contratti delle librerie','Separare contratti, unità, convenzioni e versioni per Model, Geometry, Checker e Utilities. Spostare progressivamente i calcoli residui nella libreria concordata.','Parziale','P0','T03',4,6,9,'Stesso caso produce stessi esiti da UI e chiamata diretta; DLL tracciate.','TST01; TST05','X.Calculations; lib/Checker')
task('T05','P01','Piattaforma','Dati comuni e archivio','Consolidare terreni, materiali, durabilità, ancoraggi e azioni condivise, con invalidazione, migrazione e revisioni.','Estensione','P0','T04',3,4,6,'Cambio di un dato comune aggiorna i dipendenti e conserva le revisioni.','TST05','X.Core/ProjectShared*; ProjectRevisions')
task('T06','P01','Piattaforma','Scambi e risultati uniformi','Unificare import Excel/CSV, coordinate, N-M-V-T, esiti non disponibili e metadati. Preparare identificativi stabili per BIM.','Parziale','P0','T04',3,4,6,'Round-trip senza perdita di combinazioni, unità o azioni concomitanti.','TST05','SectionActionsExcel; CalculationImports')
task('T07','P01','Piattaforma','Motore asincrono e diagnostica','Cache per input fisici, parallelismo limitato, cancellazione e diagnostica per tutti i nuovi moduli.','Estensione','P0','T04',2,3,5,'Esiti identici seriali/paralleli; risultati obsoleti non esportabili.','TST02','ConcreteReinforcementDesign.Search; ElasticPileVerificationCache')
task('T08','P02','Calcestruzzo','Sezioni generiche','Contorni poligonali, più fori, barre libere, orientamento e proprietà. Conservare sezioni rettangolari/circolari forate esistenti.','Nuova','P1','T04; T06',4,6,9,'Area, inerzie e trasformazioni verificabili; contorni invalidi respinti.','TST06','SezioneCA; SectionRegions; richiesta utente')
task('T09','P02','Calcestruzzo','Dettagli e ancoraggi comuni','Completare riuso fra sezioni, pali e muri, sovrapposizioni, zone esecutive e coerenza con esposizione SLE.','Estensione','P1','T05',3,4,6,'Medesimi dati danno medesimi esiti nei tre moduli; limiti espliciti.','TST06','ConcreteDetailing; ConcreteBond; ConcreteCoverAnalysis')
task('T10','P02','Calcestruzzo','Punzonamento','Pilastro interno, bordo e angolo; perimetri, aperture ed eccentricità. Prima versione senza/con armatura a punzonamento nei casi concordati.','Nuova','P1','T08',5,7,11,'Almeno due casi per tipologia e controllo indipendente dei perimetri.','TST06','Bozza Calcestruzzo B7')
task('T11','P02','Calcestruzzo','Inghisaggi e ancoranti','Distinguere barre post-installate e ancoranti. Definire dati di prodotto/ETA e rotture applicabili prima del calcolo.','Nuova','P1','T09',5,7,12,'Caso singolo e gruppo con distanze/bordi; nessun esito con dati di prodotto mancanti.','TST06','Bozza Calcestruzzo B8')
task('T12','P02','Calcestruzzo','Ricerca armature e risultati','Consolidare ricerca longitudinale/ortogonale/staffe, candidati alternativi, motivi di scarto, diagrammi e report short.','Estensione','P1','T07; T09',3,4,6,'Candidato applicato ricalcolato; nessuna falsa soluzione; tempi misurati.','TST02; TST06','ConcreteReinforcementDesign; ReportConcreteShort')
task('T13','P03','Geotecnica','Fondazioni superficiali autonome','Estrarre le funzioni dei muri in modulo plinti/travi rovesce: portanza, scorrimento, eccentricità, falda e sisma.','Parziale','P1','T05; T06',4,6,9,'Casi centrato/eccentrico e falda/sisma; limiti di geometria dichiarati.','TST07','RetainingWall.Serviceability; bozza Geotecnica B10')
task('T14','P03','Geotecnica','Cedimenti superficiali e molle','Cedimento immediato/consolidazione nei modelli scelti; moduli, unità e rigidezze equivalenti esportabili.','Parziale','P1','T13',4,6,10,'Confronti manuali e sensibilità stratigrafica; distinzione rigidezza/portanza.','TST07','Bozza Geotecnica B7/B11; modelli muri')
task('T15','P03','Geotecnica','Cedimenti pali e molle assiali','Palo singolo, carico-cedimento, trasferimento lungo fusto/punta e rigidezza assiale. Effetto gruppo con modello dichiarato.','Nuova','P1','T04; T14',5,8,12,'Due casi analitici/di letteratura e prova di sensibilità fusto-punta.','TST07','Bozza Geotecnica B7/B8')
task('T16','P03','Geotecnica','Pali e muri: completamento operativo','Consolidare tratti armati, giunti, nodi palo-plinto, distinte e cautele. Definire separatamente eventuale modello resistente delle spirali.','Estensione','P1','T09; T15',3,5,8,'Tre progetti reali, dettagli mancanti riconoscibili e nessun esito globale improprio.','TST03; TST07','ElasticHorizontalPile; RetainingWall.BarSchedule')
task('T17','P04','Azioni','Casi di carico e combinazioni','Dizionario G/Q, gruppi esclusivi, coefficienti e famiglie SLU/SLE/sismiche; origine delle azioni e inviluppi concomitanti.','Nuova','P1','T06',3,5,7,'Combinazioni ripercorribili e nessun inviluppo fittizio N-M-V-T.','TST08','Bozza Azioni; import azioni già presente')
task('T18','P04','Azioni','Vento','Velocità/pressione, esposizione, coefficienti e geometrie iniziali concordate; report del percorso di calcolo.','Nuova','P1','T17',3,4,6,'Due esempi e sensibilità quota/esposizione; casi fuori campo segnalati.','TST08','Bozza Azioni B3')
task('T19','P04','Azioni','Temperatura e neve','Azioni uniformi e gradienti termici; neve con quota, forma e accumuli nei casi selezionati.','Nuova','P1','T17',4,6,9,'Due casi termici e due neve; unità e segni provati.','TST08','Bozza Azioni B4/B5')
task('T20','P04','Azioni','Traffico e carichi mobili','Schemi di carico, corsie e posizioni per ponti; generazione azioni/scambi. Analisi globale completa esclusa da questa attività.','Parziale','P1','T17',5,7,11,'Carico mobile confrontato su trave campione, posizioni governanti tracciate.','TST08','Bozza Azioni B6; Bridge Design preliminare')
task('T21','P05','Acciaio','Materiali e sezioni autonome','Cataloghi, proprietà lorde ed efficaci, classificazione 1–4, sezioni saldate e composte; evitare doppioni del motore ponti.','Parziale','P1','T04; T06',4,6,9,'Proprietà confrontate con cataloghi e casi manuali, assi locali verificati.','TST09','Bozza Acciaio B2/B3; BridgeSection.Properties')
task('T22','P05','Acciaio','Resistenza delle sezioni','N-Mx-My-V-T e interazioni per le classi previste; rendere visibili i limiti della classe 4.','Parziale','P1','T21',5,7,10,'Casi elastici/plastici ed efficaci con controlli indipendenti.','TST09','Bozza Acciaio B4/C5/C6')
task('T23','P05','Acciaio','Stabilità aste e pannelli','Instabilità flessionale/flesso-torsionale, laterale e pannello anima; vincoli e lunghezze efficaci espliciti.','Parziale','P1','T22',5,7,11,'Compressione, trave e pannello, con almeno due condizioni di vincolo.','TST09','Bozza Acciaio B10; controlli locali ponti')
task('T24','P05','Acciaio','Connessioni e coprigiunti','Prima famiglia: giunti bullonati e saldati, coprigiunti, verifiche componenti, distanze e disegno schematico.','Nuova','P1','T22',6,8,13,'Due schemi di giunto e controllo manuale delle rotture applicabili.','TST09','Bozza Acciaio B7/C8')
task('T25','P06','Misto e ponti','Classe 4 e metodi di analisi','Consolidare proprietà efficaci, verifiche locali e matrice di copertura fra cumulativo e metodi con storico.','Estensione','P1','T22; T23',4,6,9,'Ogni metodo dichiara ciò che verifica e ciò che resta da completare.','TST10','BridgeSection; guida metodi e limiti')
task('T26','P06','Misto e ponti','Travata e collegamento delle fasi','Trasferire geometrie, fasi e azioni dal progetto alle sezioni locali, con riferimenti di stazione e confronto degli stati.','Parziale','P1','T20; T25',5,8,12,'Ponte campione con tre sezioni, azioni da analisi esterna e trasferimento senza ambiguità.','TST10','Bozza Misto B4; Bridge Design non trasferisce modello verificato')
task('T27','P06','Misto e ponti','Predalles e soletta per fasi','Elemento prefabbricato, getto integrativo, materiali e armature propri, puntellamento, interfaccia e fasi di montaggio.','Parziale','P1','T09; T25',5,7,11,'Due sequenze di costruzione e confronto con/senza puntelli.','TST10','Bozza Misto B5; BridgeSection.SlabLayout')
task('T28','P06','Misto e ponti','Connettori e fatica selezionata','Scorrimento longitudinale, connettori e dettagli di fatica scelti; censire ciò che esiste nel Checker prima di estendere.','Parziale','P2','T24; T25',5,8,13,'Due casi per controllo attivato, storico/cicli e categoria di dettaglio tracciati.','TST10','Bozza Misto B3/B4; estensione proposta')
task('T29','P06','Misto e ponti','Bridge Design e confronti','Consolidare ottimizzazione, sensibilità prezzi/CO₂, fattibilità e passaggio delle alternative al flusso analitico.','Estensione','P2','T26',3,4,6,'Alternative riproducibili, obiettivi dichiarati e separazione predimensionamento/verifica.','TST10','BridgeConcept; suite IndependentChecks')
task('T30','P07','CAP','Materiali e tracciato dei cavi','Proprietà trefoli, pretensione/post-tensione, aderenza, eccentricità e fasi. Scegliere i casi iniziali.','Parziale','P2','T04; T25',4,6,9,'Due sezioni precompresse e gestione chiara delle unità e della predeformazione.','TST11','Bozza CAP vuota; trefoli sezionali esistenti')
task('T31','P07','CAP','Perdite e storia della precompressione','Attrito, rientro, accorciamento, viscosità, ritiro e rilassamento; successione temporale documentata.','Nuova','P2','T30',5,8,13,'Confronto perdite istantanee/differite e bilancio della forza per fase.','TST11','Guide: perdite non ricostruite automaticamente')
task('T32','P07','CAP','Verifiche CAP','SLU/SLE, decompressione, fessurazione e taglio con contributi dei cavi; limiti espliciti delle zone di ancoraggio.','Parziale','P2','T31; T09',5,8,13,'Nessuna applicazione implicita delle regole CA al CAP; test per ogni controllo.','TST11','ConcreteShearAnalysis; Ntc2018Checks: CAP da completare')
task('T33','P07','CAP','Interfaccia e caso pilota','Vista cavi/fasi, confronto ipotesi, report e caso reale di trave o impalcato concordato.','Nuova','P2','T32',3,4,6,'Calcolo salvato-riaperto riproduce fasi, perdite e risultati.','TST03; TST11','Estensione proposta')
task('T34','P08','Rilascio','Collaudo integrato','Tre progetti trasversali, compatibilità archivi, installazione pulita, dipendenze e prestazioni.','Estensione','P0','T16; T19; T29; T33',3,5,8,'Tutti i criteri di rilascio soddisfatti e difetti residui accettati.','TST12','Suite e installer esistenti')
task('T35','P08','Rilascio','Documenti e librerie distribuite','Allineare guide globali, dossier di validazione, esempi, manifest DLL, note di rilascio e pacchetto installabile.','Estensione','P0','T34',2,3,5,'Versioni e risultati concordanti tra app, report e documentazione.','TST12','Guide Rev30; installer; lib/Checker/manifest.json')
task('T36','P08','Rilascio','Feedback finale e stabilizzazione','Sessione operativa assistita, correzioni prioritarie e accettazione del rilascio funzionale.','Estensione','P0','T35',2,3,5,'Approvazione del referente tecnico, backlog residuo ordinato.','TST03; TST12','Estensione proposta')
task('T37','B01','BIM','Contratto BIM e casi pilota','Oggetti supportati, GUID, unità, coordinate, revisione, mapping materiali, responsabilità del dato e profilo IFC scambiabile.','Nuova','P1','T06; T36',3,5,7,'Due modelli campione, uno Revit e uno Tekla, con dizionario dati approvato.','TST13','IFC ufficiale; proposta architetturale')
task('T38','B01','BIM','Import IFC selettivo','Leggere elementi, geometrie e proprietà del perimetro pilota. Anteprima delle associazioni e quarantena dei dati incompleti.','Nuova','P1','T37',5,8,12,'Identità, assi, unità, fori e sezioni confrontati su entrambi i modelli.','TST13','IFC 4.3; profilo da validare nei due software')
task('T39','B01','BIM','Esiti e requisiti informativi','Esportare collegamenti ai report e proprietà di verifica. IDS per dati richiesti; BCF per anomalie e osservazioni.','Nuova','P1','T38',3,5,8,'Oggetto errato produce segnalazione localizzabile; nessun esito senza combinazione/revisione.','TST13','IDS; BCF ufficiali')
task('T40','B02','BIM Revit','Lettura e associazione Revit','Connettore per elementi selezionati, sezioni/materiali, modello fisico/analitico e identificativi persistenti.','Nuova','P1','T39',5,7,11,'Import ripetuto non duplica oggetti; disallineamenti fisico/analitico espliciti.','TST14','Autodesk Revit API')
task('T41','B02','BIM Revit','Restituzione armature ed esiti','Parametri di verifica, report e prima famiglia di armature approvate. Anteprima e transazione annullabile.','Nuova','P1','T40; T09',5,8,13,'Copriferri, diametri, quantità e pieghe confrontati; elementi non supportati esclusi.','TST14','Autodesk Revit API; proposta')
task('T42','B02','BIM Revit','Pilota e feedback Revit','Installazione, compatibilità versione scelta, prova operatore e aggiornamento del modello dopo una modifica.','Nuova','P1','T41',3,4,6,'Andata/ritorno su modello pilota senza perdita di identità o unità.','TST14','Proposta; modello Revit utente')
task('T43','B03','BIM Tekla','Lettura e associazione Tekla','Connettore per parti, profili, materiali e gruppi armatura; riuso contratto e risultati comuni.','Nuova','P1','T39; T42',5,7,11,'Import ripetuto idempotente; orientamenti e materiali confrontati.','TST15','Tekla Open API')
task('T44','B03','BIM Tekla','Armature, distinte e risultati','Prima famiglia di barre/staffe, attributi di verifica e confronto quantità. Applicazione solo dopo conferma dell’operatore.','Nuova','P1','T43; T09',5,8,13,'Pieghe, lunghezze e quantità confrontate con distinta ANTHEA e modello.','TST15','Tekla Open API; proposta')
task('T45','B03','BIM Tekla','Pilota e feedback Tekla','Compatibilità versione scelta, prova con modellatore e aggiornamento incrementale del progetto.','Nuova','P1','T44',3,4,6,'Andata/ritorno verificato sul modello pilota e installazione ripetibile.','TST15','Proposta; modello Tekla utente')
task('T46','B04','BIM','Revisioni e conflitti','Confronto prima/dopo, mappa delle modifiche, proprietà possedute dai diversi sistemi e scelta del dato da mantenere.','Nuova','P1','T42; T45',5,7,11,'Modifica concorrente rilevata; nessuna sovrascrittura silenziosa.','TST16','ProjectRevisions; proposta')
task('T47','B04','BIM','Coordinamento e scambio BCF','Gestire segnalazioni aperte/risolte, collegamenti agli oggetti e alle versioni dei report nei due software.','Nuova','P1','T46',3,5,8,'Issue riaperta mantiene GUID, vista, autore e versione del calcolo.','TST16','BCF ufficiale')
task('T48','B04','BIM','Collaudo BIM e consegna','Progetto completo Revit e Tekla, conflitti, dati mancanti, prestazioni, manuali e manutenzione dei connettori.','Nuova','P0','T47',3,5,8,'Accettazione di tecnico e modellatore su entrambi gli ambienti.','TST16','Proposta')

inventory=[
('S01','Progetti','Struttura gerarchica e sottogruppi','Presente','Progetti, fogli, materiali/terreni condivisi, revisioni e report di ramo.','Consolidare migrazioni e dipendenze.','Guida pratica §Progetti; X.Core/ProjectSharedHierarchy.cs','T05'),
('S02','Materiali','CLS e durabilità','Presente','Materiali, esposizioni, copriferro e legami costitutivi modificabili.','Estendere il catalogo senza duplicare i dati.','ModuleCatalog; ConcreteMaterials; Materials/NtcCover','T05'),
('S03','Materiali','Acciaio per armature','Presente','Scheda dedicata e diagrammi anche per materiali di default.','Acciaio strutturale autonomo ancora da sviluppare.','ModuleCatalog; RebarMaterial','T21'),
('S04','Calcestruzzo','Geometrie e fori centrali','Presente','Rettangolo, T e circolare; fori centrali rettangolari/circolari; lati del cerchio configurabili.','Contorni poligonali e fori multipli futuri.','SezioneCA; SectionGeometry','T08'),
('S05','Calcestruzzo','Domini e resistenze NMM','Presente','2D/3D, SLU/SLV, punto resistente, piani deformativi e tensioni.','Consolidare casi limite e convenzioni.','CheckerSection; SectionMomentResistance','T02'),
('S06','Calcestruzzo','SLE e fessurazione','Presente','Tensioni, fessurazione, aree efficaci e tracce nel perimetro CA documentato.','CAP e fessurazione non lineare non considerati coperti.','Ntc2018Checks; ConcreteTensionCracking','T32; O01'),
('S07','Calcestruzzo','Taglio e torsione','Presente con limiti','Due direzioni, circolari con modello esplicito, torsione e interazione previste dal modulo.','Taglio CAP e spirali dei pali da completare.','ConcreteShearAnalysis; ConcreteTorsion','T16; T32'),
('S08','Calcestruzzo','Dettagli, ancoraggi, M-curvatura','Presente','Dettagli per elemento, ancoraggi/sovrapposizioni, curve M-curvatura.','Unificare riuso e dettagli esecutivi fra moduli.','ConcreteDetailingAnalysis; ConcreteBond; ConcreteCurvatureAnalysis','T09'),
('S09','Calcestruzzo','Ottimizzazione armature','Presente','Longitudinale, ortogonale e staffe, alternative, obiettivi e controlli preventivi.','Misurare prestazioni e robustezza su casi reali.','ConcreteReinforcementDesign; suite Checks','T12'),
('S10','Calcestruzzo','Report short','Presente','Word/PDF entro due pagine, sette verifiche governanti, esiti incompleti distinti.','Richiede Word; verificare con casi estesi.','ReportConcreteShort; ConcreteShort.Checks','T03'),
('S11','Geotecnica','Pali e micropali verticali','Presente','Capacità assiale, stratigrafie, falda, coefficienti e abachi previsti.','Cedimenti e molle assiali dedicati futuri.','ModuleCatalog; Calcolo; Micropali','T15'),
('S12','Geotecnica','Capacità orizzontale','Presente','Pali/micropali con Broms e sezione CHS; limiti dichiarati.','Non equivale a risposta p-y non lineare.','PaloOrizzontale; MicropaloOrizzontale','O02'),
('S13','Geotecnica','Palo elastico e armature','Presente con limiti','Risposta elastica stratificata, tratti, verifiche e dettagli sismici di testa.','Esclusi p-y, ciclicità, secondo ordine e nodo palo-plinto completo.','ElasticHorizontalPile; guida pratica §Risposta elastica','T16; O02'),
('S14','Geotecnica','Palificata orizzontale','Presente con limiti','Efficienza di gruppo con sei teorie.','Non è soluzione strutturale completa del gruppo.','HorizontalPileGroup; ModuleCatalog','O02'),
('S15','Geotecnica','Muri di sostegno','Presente con limiti','Spinte, verifiche locali/globali, portanza/cedimenti, armature e distinte.','Fondazioni superficiali autonome da estrarre/consolidare.','RetainingWall; guide Rev30','T13; T14; T16'),
('S16','Misto','Sezione composta da ponte','Presente con limiti','Classe 4, fasi, cumulativo e storici, curve di risposta e controlli locali.','Copertura diversa tra metodi; non è analisi globale dell’intero ponte.','BridgeSection; guida §Sezione composta','T25; T26'),
('S17','Misto','Predalle','Parziale','Riferimento geometrico della soletta.','Nessun materiale/fase/verifica autonomi della predalle.','BridgeSection.SlabLayout: PredalleScope','T27'),
('S18','Ponti','Bridge Design','Presente con limiti','Predimensionamento, alternative, quantità, costi e CO₂.','Trasferimento a modello verificato non automatico.','BridgeConcept; guida §Bridge Design','T26; T29'),
('S19','CAP','Trefoli in sezione','Parziale','Trefoli e predeformazioni previste dal motore sezionale.','Perdite, taglio e fessurazione CAP completi non disponibili.','CheckerSection; Ntc2018Checks; ConcreteShearAnalysis','T30–T33'),
('S20','Acciaio','Modulo autonomo e connessioni','Non riscontrato','Proprietà e controlli riutilizzabili nel motore ponti.','Non confondere la presenza di librerie con un modulo operativo completo.','ModuleCatalog; BridgeSection','T21–T24'),
('S21','Azioni','Vento, neve, temperatura, traffico','Non completo','Import azioni e funzioni specifiche nei ponti.','Manca una suite autonoma unificata di generazione e combinazione.','ModuleCatalog; SectionActionsExcel','T17–T20'),
('S22','Qualità','Guide, Wiki, test e distribuzione','Presente','Due guide globali Rev30, Wiki, esempi, test e installer.','Questa ricognizione non riesegue tutte le suite né dichiara una nuova validazione.','supporto/README; supporto/test; supporto/installer','T01–T03; T34–T36'),
('S23','BIM','IFC, Revit e Tekla','Non riscontrato','Dati e revisioni del progetto riutilizzabili come base.','Connettori e flusso BIM sono proposte future.','ModuleCatalog; ricognizione sorgenti','T37–T48')]

tests=[
('TST01','Ogni modifica al motore','Sviluppatore + referente tecnico','Regressione numerica','Casi esistenti conservati; almeno due esempi indipendenti per nuovo controllo più casi limite.','Tolleranze definite prima del test, scarti spiegati, nessun peggioramento non approvato.','Dati, valori attesi, versione DLL, log e confronto.','P00; tutte le fasi'),
('TST02','Prima/dopo ottimizzazioni','Sviluppatore','Prestazioni e concorrenza','Casi piccoli/medi/grandi, tre ripetizioni, tempi p50/p95, RAM, cancellazione e determinismo.','Budget fissato con la baseline; regressione >10% da spiegare; nessuna UI bloccata nei flussi concordati.','Misure sulla stessa macchina e input.','P00; P01; P02; B04'),
('TST03','Ogni 10 giornate di lavoro','Utente + sviluppatore','Demo e feedback operativo','30–45 minuti, un caso reale, tre problemi/priorità principali. Con 5 gg/settimana: circa ogni 2 settimane; con 2 gg: circa ogni 5.','Feedback registrato e classificato; priorità e prossimo obiettivo concordati.','Registro feedback con responsabile, decisione e criterio di chiusura.','Tutte le fasi'),
('TST04','A ogni modifica UI/report','Sviluppatore + utente','Leggibilità e correttezza visiva','Segni, unità, selettori, contour, viste, schermate piccole e report completi/short.','Vista coerente con opzione; nessun dato tagliato; esito coerente con risultati numerici.','Schermate e PDF controllati.','P00; P02; tutte le UI'),
('TST05','Ogni modifica contratti/archivio','Sviluppatore','Dati e compatibilità','Salva-riapri, versioni vecchie, unità, duplicati, condivisione, invalidazione e batch.','Nessuna perdita silenziosa; errori localizzati; risultati obsoleti bloccati.','Archivio prima/dopo e confronto strutturato.','P01; ogni rilascio'),
('TST06','Prima di M02','Tecnico strutturista + sviluppatore','Calcestruzzo','NMM, fori, tensione totale, taglio/torsione, dettagli, punzonamento, inghisaggi.','Esempi ripercorribili; campi fuori modello espliciti; dettaglio applicato ricalcolato.','Schede di confronto e progetto pilota.','P02'),
('TST07','Prima di M03','Referente geotecnico + sviluppatore','Geotecnica','Portanza/cedimenti, falda, stratigrafie, molle, gruppo, vincoli e tratti armati.','Equilibrio, unità e convergenza controllati; limiti del modello leggibili.','Confronti manuali/letteratura e sensibilità.','P03'),
('TST08','Prima di M04','Tecnico + sviluppatore','Azioni e combinazioni','Segni, gruppi esclusivi, posizioni mobili, duplicati, estremi e concomitanza.','Conteggio combinazioni e massimi riproducibili su schemi semplici.','Elenco carichi/combinazioni e confronto indipendente.','P04'),
('TST09','Prima di M05','Tecnico acciaio + sviluppatore','Acciaio','Classi 1–4, instabilità, pannelli, giunti, bulloni e saldature.','Nessuna modalità di rottura applicabile omessa; almeno due esempi per controllo.','Schede benchmark e distinta geometrica.','P05'),
('TST10','Prima di M06','Tecnico ponti + sviluppatore','Misto e ponti','Fasi, creep/ritiro, efficacia, travata, predalle, connettori e fatica concordata.','Fasi e azioni locali tracciate; nessun esito trasferito fuori dal campo del metodo.','Ponte campione e tre sezioni rappresentative.','P06'),
('TST11','Prima di M07','Tecnico CAP + sviluppatore','Precompressione','Perdite, cavi, tensionamento, SLE/SLU e taglio.','Bilancio della precompressione e segni corretti; casi indipendenti concordati.','Trave pilota e tabella delle fasi.','P07'),
('TST12','Prima di M08','Utente + sviluppatore','Accettazione del rilascio','Tre progetti reali, installazione pulita, guide e report, regressioni e migrazioni.','Zero difetti bloccanti/gravi sui flussi inclusi; altri difetti esplicitamente accettati.','Verbale di accettazione, pacchetto e backlog residuo.','P08'),
('TST13','Prima di MB1','Modellatore BIM + tecnico','IFC e requisiti dati','Modelli Revit/Tekla: GUID, unità, coordinate, sezioni, fori e materiali; requisiti mancanti.','100% oggetti del pilota mappati o respinti con motivazione; nessuna correzione implicita.','IFC originali, mapping, esiti IDS e segnalazioni BCF.','B01'),
('TST14','Prima di MB2','Modellatore Revit + tecnico','Connettore Revit','Fisico/analitico, parametri, barre, copia modello, cancellazione e modifica successiva.','Round-trip concordato, quantità confrontate e rollback provato.','Modello prima/dopo e verbale utente.','B02'),
('TST15','Prima di MB3','Modellatore Tekla + tecnico','Connettore Tekla','Profili, parti, attributi e armature; unità/orientamenti; modifica e riimport.','Idempotenza, distinte confrontate e rollback provato.','Modello prima/dopo e verbale utente.','B03'),
('TST16','Prima di MB4 e a ogni aggiornamento API','BIM coordinator + tecnico + sviluppatore','Conflitti e interoperabilità','Modifiche concorrenti, proprietà non possedute, revisione calcolo, BCF e report.','Nessuna sovrascrittura silenziosa; nessun risultato marcato valido dopo modifica rilevante.','Registro conflitti e due progetti pilota finali.','B04')]

bim=[
('BIM01','Architettura','Nucleo comune + due adattatori','ANTHEA mantiene dati di calcolo, ipotesi, esiti e revisioni. Revit e Tekla mantengono il modello costruttivo secondo una matrice di responsabilità. IFC scambia dati neutri.','T37','Proposta ANTHEA'),
('BIM02','Identità','Mappa persistente degli oggetti','GUID IFC + ID nativo + ID ANTHEA + revisione/hash dei dati. Gestire copie, cancellazioni e fusioni senza affidarsi al solo nome.','T37; T46','Proposta ANTHEA'),
('BIM03','Geometria','Fisico e analitico distinti','Trasformazioni globali/locali, unità, orientamenti, offset e sezione resistente. In Revit verificare le associazioni fra modello fisico e analitico.','T38; T40','Autodesk API; IFC'),
('BIM04','Dati necessari','Contratto prima dello scambio','Materiale, geometria, armatura, copriferro, esposizione, riferimento azioni, metodo e versione. IDS per proprietà obbligatorie; controlli ANTHEA per coerenza meccanica.','T37; T39','IDS; proposta ANTHEA'),
('BIM05','Primo pilota','Sezione CA e un elemento ripetuto','Scegliere pilastro/palo o muro semplice con due revisioni. Prima lettura e verifica, poi restituzione controllata; estendere ai ponti dopo il pilota.','T38–T45','Proposta ANTHEA'),
('BIM06','Revit','Connettore dedicato','Seleziona elementi, mappa materiali/sezioni, apre il foglio ANTHEA; restituisce parametri, link al report e armature della prima famiglia supportata.','T40–T42','Autodesk Revit API'),
('BIM07','Tekla','Connettore dedicato','Seleziona parti e gruppi armatura, associa profili/materiali, restituisce attributi, armature e distinte confrontabili.','T43–T45','Tekla Open API'),
('BIM08','Conferma delle modifiche','Anteprima e annullamento','Mostrare geometria/armature prima e dopo, proprietà modificate e incompatibilità. Applicare solo la proposta selezionata; registrare e poter annullare.','T41; T44; T46','Proposta ANTHEA'),
('BIM09','Esiti nel modello','Proprietà di verifica tracciate','Eta, stato, famiglia, combinazione governante, revisione calcolo, versione software, data e report. Una geometria aggiornata invalida i risultati correlati.','T39; T46','Proposta ANTHEA'),
('BIM10','Feedback BIM','BCF per problemi e revisioni','Associare problema, oggetto, vista e riferimento alla verifica. Tracciare apertura, decisione, correzione e nuova verifica. BCF non sostituisce un motore di calcolo.','T39; T47','BCF ufficiale'),
('BIM11','IFC','Profilo negoziato con i due software','Valutare IFC4 e IFC4.3 per il perimetro previsto, soprattutto infrastrutture. Provare gli scambi effettivi; non presumere che ogni oggetto o proprietà sia supportato in entrambe le applicazioni.','T37; T38','IFC 4.3.2.0 ufficiale'),
('BIM12','Azioni','Origine separata della domanda','Non dedurre automaticamente N-M-V-T dalla sola geometria BIM. Importare azioni dall’analisi con ID elemento, stazione, assi, unità e combinazione.','T06; T26; T37','Proposta ANTHEA'),
('BIM13','Ambiente e licenze','Versioni da concordare al kickoff BIM','Indicare versioni Revit/Tekla, SDK, licenze di sviluppo e due modelli disponibili. Prevedere manutenzione quando cambiano le API.','T37; T48','Autodesk e Tekla ufficiali'),
('BIM14','Successivi ampliamenti','Dopo accettazione MB4','CDE/API collaborative, coordinamento multidisciplinare, quantità/costi/CO₂ collegati, ponti complessi e automazioni di disegno. Non inclusi nel pilota corrente.','O04','Proposta ANTHEA')]

options=[
('O01','Fessurazione non lineare e ciclicità CA','Rinviata su indicazione precedente dell’utente; definire modello e benchmark prima di attivare.',10,16,25,'M02'),
('O02','Pali p-y, risposta ciclica e gruppo accoppiato','Estensione non lineare distinta da Broms e dal palo elastico; richiede parametri e casi sperimentali.',15,24,40,'M03'),
('O03','Solutore FEM globale generalista','Telai/piastre/gusci, analisi sismiche e non lineari sono un progetto autonomo. Prima fase consigliata: import da solutori esistenti.',40,70,120,'M06'),
('O04','BIM esteso e CDE','Ponti complessi, sincronizzazione multiutente, server BCF/CDE e automazioni avanzate di disegno.',15,25,45,'MB4'),
('O05','Verifiche specialistiche aggiuntive','Incendio, strutture esistenti, FRC, rinforzi, fatica estesa e certificazioni richiedono singoli capitolati; stima da formulare dopo scelta.',None,None,None,'Da definire')]

sources=[
('F01','Bozza utente','00-Programma.xlsx','Sette fogli; CAP vuoto; le voci sono richieste di prodotto, non istruzioni operative.','X:/ITEC-MODELLI/99-AI/00-Programma/00-Programma.xlsx'),
('F02','Stato applicazione','Catalogo moduli','Ricognizione dei moduli registrati al 06/10/2026; presenza distinta dalla validazione.','X.Calculations/ModuleCatalog.cs'),
('F03','Uso e limiti','Guide globali Rev30','Guida pratica e teorica, in particolare CLS, ponti, geotecnica e progetti.','supporto/docs/guida-pratica-anthea.md; supporto/docs/guida-teorica-anthea.md'),
('F04','Qualità','Suite e documentazione esistenti','Test presenti e report di attività, non rieseguiti integralmente per questo programma.','supporto/test; supporto/README.md'),
('F05','Predalle','Campo attuale','Riferimento geometrico, non elemento verificato autonomamente.','X.Calculations/BridgeSection.SlabLayout.cs'),
('F06','CAP','Esclusioni esplicite','Taglio CAP e apertura fessure CAP non completati nei percorsi consultati.','X.Calculations/ConcreteShearAnalysis.cs; X.Calculations/Ntc2018Checks.cs'),
('F07','BIM','IFC 4.3.2.0','Schema ufficiale consultato il 06/10/2026; proposta di profilo da collaudare nei software.','https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/'),
('F08','BIM','IDS','Requisiti informativi leggibili da software; consultato il 06/10/2026.','https://technical.buildingsmart.org/projects/information-delivery-specification-ids/'),
('F09','BIM','BCF','Scambio di problemi associati al modello; consultato il 06/10/2026.','https://technical.buildingsmart.org/standards/bcf/'),
('F10','BIM','Revit API: analytical model','Associazione fra elementi fisici e analitici; consultato il 06/10/2026.','https://help.autodesk.com/cloudhelp/2026/ENU/Revit-API-MainReference/files/html/d586b341-f687-9d90-e96d-255806b7d4fc.htm'),
('F11','BIM','Tekla Open API','Accesso ai modelli/disegni e integrazione con altri strumenti; consultato il 06/10/2026.','https://developer.tekla.com/documentation/where-use-tekla-structures-open-api'),
('F12','BIM','Licenze Tekla Open API','Prerequisiti ufficiali di sviluppo; consultato il 06/10/2026.','https://developer.tekla.com/documentation/get-started-tekla-structures-open-api'),
('F13','Stime','Stime proposte con AI','Giudizio di pianificazione al 06/10/2026, non velocità storica misurata né impegno contrattuale. Da calibrare a M00.','Elaborazione del programma')]

mapping={
'Azioni':{3:('Non completo','T18'),4:('Non completo','T19'),5:('Non completo','T19'),6:('Parziale','T20')},
'Acciaio':{2:('Parziale','T21'),3:('Parziale','T21'),4:('Parziale','T22'),5:('Parziale','T22'),6:('Parziale','T22'),7:('Non riscontrato','T24'),8:('Non riscontrato','T24'),10:('Parziale','T23')},
'Calcestruzzo':{3:('Presente','S02'),4:('Presente','S08; T09'),5:('Presente','S05; S06'),6:('Presente con limiti','S07'),7:('Non riscontrato','T10'),8:('Non riscontrato','T11')},
'Misto':{3:('Presente con limiti','S16; T25'),4:('Parziale','T26'),5:('Parziale','S17; T27')},
'Geotecnica':{3:('Presente','S11'),4:('Presente','S12; S13'),5:('Presente','S11'),6:('Presente','S12'),7:('Parziale','T14; T15'),8:('Non riscontrato','T15'),9:('Presente','S15'),10:('Parziale','T13'),11:('Parziale','T14')},
'Sezione progetto':{3:('Presente','S01'),4:('Presente','S01; T05')}}
original=[]
w=openpyxl.load_workbook(OUT/'bozza-originale.xlsx',data_only=False)
for s in w:
    found=False
    for i,row in enumerate(s.iter_rows(values_only=True),1):
        if not any(v is not None for v in row):continue
        found=True
        label=next((str(x) for x in reversed(row) if isinstance(x,str) and not x.startswith('=')), '')
        status,ids=mapping[s.title][i]
        original.append([s.title,i,label,status,ids])
    if not found: original.append([s.title,1,'Foglio vuoto nella bozza','Da definire','T30–T33'])

assert len({t['id'] for t in tasks})==len(tasks)
seen=set()
for t in tasks:
    for d in t['deps'].split('; '):assert d=='—' or d in seen,(t['id'],d)
    seen.add(t['id']);assert t['lo']<=t['base']<=t['hi']
payload=dict(asof='2026-10-06',start='2026-10-12',capacity_full=5,capacity_part=2,reserve=.20,phases=phases,tasks=tasks,inventory=inventory,tests=tests,bim=bim,options=options,sources=sources,original=original,
    feedback=[['FB01','Da compilare','','','','','','']],
    assumptions=[
    'Una sola persona sviluppa con AI in entrambi gli scenari. Tempo pieno = 5 giornate/settimana; parziale = 2. Nessun parallelismo fra fasi nella baseline.',
    'Le giornate sono impegno residuo stimato: includono analisi, codice assistito da AI, test di modulo, correzioni ordinarie, documenti e preparazione demo. Le funzioni già presenti non sono conteggiate da ricostruire.',
    'Minimo/base/massimo sono stime per attività. Il margine del 20% copre imprevisti e integrazione trasversale, oltre alle attività previste. Non è una probabilità statistica.',
    'Calendario ipotetico da lunedì 12/10/2026, modificabile. Settimane arrotondate per fase. Ferie, festività e sospensioni non sono modellate. Date di lungo periodo sono orientative.',
    'Il referente tecnico, esterno alla capacità di sviluppo, prepara i casi e restituisce feedback entro due giorni lavorativi. Attese ulteriori spostano le milestone; l’AI non sostituisce l’accettazione tecnica.',
    'Le stime BIM includono entrambi i connettori, una versione per software e una famiglia iniziale di elementi/armature. Versioni, modelli pilota e licenze sono da concordare a MB1.',
    'P0 = prerequisite/affidabilità; P1 = obiettivo del programma; P2 = ampliamento da confermare alla milestone precedente. Le opzioni O01–O05 sono escluse dai totali e dal calendario.',
    'Stato ricostruito da sorgenti e guide Rev30 al 06/10/2026. Presente significa funzione implementata/documentata nel suo campo, non nuova attestazione di validazione. La validazione esistente è assunta attendibile secondo l’indicazione dell’utente.'
    ])
(OUT/'contenuti.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2),encoding='utf-8')
print('Attività',len(tasks),'stato',len(inventory),'voci bozza',len(original),'giorni',*[sum(t[k] for t in tasks) for k in ('lo','base','hi')])
