<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ANTHEA</AssemblyName>
    <Product>ANTHEA</Product>
    <Title>ANTHEA</Title>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../X.Core/X.Core.csproj" /></ItemGroup>
  <ItemGroup><Reference Include="../lib/Checker/*.dll" /></ItemGroup>
  <ItemGroup><Resource Include="Assets/*.png" /></ItemGroup>
</Project>
