<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>ANTHEA.Verifiche</AssemblyName><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../X.Core/X.Core.csproj" /></ItemGroup>
  <ItemGroup>
    <Reference Include="../../../lib/Checker/*.dll" Exclude="../../../lib/Checker/GPCChecker.CompositeBridge.dll" />
    <Reference Include="GPCChecker.CompositeBridge"><HintPath>../../../lib/Checker/GPCChecker.CompositeBridge.dll</HintPath><Private>true</Private></Reference>
  </ItemGroup>
</Project>
