using System.Windows.Controls;
using X.Core;

namespace X.Desktop;

internal sealed partial class BridgeWorkspace
{
    private void ShowModelInformation()
    {
        var content = Ui.Stack(
            Ui.Text("Come viene analizzata la sezione da ponte", 20, true),
            Ui.Text("Gli schemi spiegano il modello implementato; sono illustrativi e non rappresentano i dati della sezione aperta. Le tensioni vengono risolte con Model e Checker; il ciclo delle larghezze efficaci è nel modulo ANTHEA.", 13),
            Group("01 · Fasi di carico e somma delle tensioni", Ui.Stack(new BridgeMethodSketch(0),
                Ui.Text("Ogni riga contiene un incremento ΔN e ΔMx già combinato. La situazione «Dopo fase i» comprende quella riga e tutte le precedenti attive. Il tipo di sezione stabilisce quali materiali reagiscono: solo acciaio; composta non fessurata; oppure acciaio e armature con soletta esclusa.", 13),
                Ui.Text("Per ciascuna situazione si ricalcolano tutti i contributi sulla stessa carpenteria efficace. La somma si esegue sulle tensioni dei singoli materiali, non direttamente sui piani grezzi di deformazione di Checker. Cambiando la situazione può cambiare anche la sezione efficace usata per i contributi precedenti.", 13),
                Notice("Questo modello non congela le tensioni raggiunte durante la costruzione e non simula una redistribuzione viscosa nel tempo. È una sovrapposizione elastica per situazioni di verifica.")), true),
            Group("02 · Omogeneizzazione e materiali", Ui.Stack(new BridgeMethodSketch(1),
                Ui.Text("Le proprietà A*, yG e Ix* sono riferite all’acciaio strutturale. La soletta contribuisce con Ec,eff = Ecm / (1 + ψL·φ); il suo rapporto modulare è n = Ea / Ec,eff. Le barre usano Es/Ea e sostituiscono l’area corrispondente di calcestruzzo.", 13),
                Ui.Text("φ, ψL e n sono modificabili in ogni fase composta: assegnare n aggiorna φ; assegnare φ o ψL aggiorna n. Il valore passato alle API di Model e Checker è il prodotto ψL·φ. I due acciai possono avere moduli diversi. Il grafico usa ψL = 1,1 soltanto come esempio della relazione.", 13)), true),
            Group("03 · Punto di applicazione N e riferimento dei momenti", Ui.Stack(new BridgeMethodSketch(2),
                Ui.Text("N è normale al piano della sezione e agisce sull’asse di simmetria. y = 0 è l’interfaccia tra soletta e carpenteria; y cresce verso l’alto. N positivo è trazione, Mx positivo comprime la parte superiore. ΔMx è riferito al punto N della stessa fase.", 13),
                Ui.Text("Quota comune: tutte le fasi che la selezionano usano il valore y inserito. Baricentro omogeneizzato lordo: yN è ricavato dai materiali reagenti e dal fattore n di quella fase, prima delle riduzioni locali, e resta fisso nel ciclo. È la scelta iniziale delle nuove fasi.", 13),
                Ui.Text("Baricentro efficace iterativo: yN segue il baricentro della fase a ogni aggiornamento della carpenteria efficace. È un’ipotesi di carico centrato sulla sezione efficace corrente; a geometria efficace diversa corrisponde un diverso punto di applicazione.", 13),
                Ui.Text("Trasporto al baricentro corrente: Mx,G = Mx + N·(yG − yN). Per sommare fasi con quote diverse si usa il riferimento comune y = 0: Mx,0 = Mx − N·yN. N in kN e y in mm richiedono la divisione per 1000 per ottenere kNm. Le tabelle espongono yN di ogni contributo e i momenti cumulati a y = 0.", 13)), true),
            Group("04 · Classe 4 e convergenza", Ui.Stack(new BridgeMethodSketch(3),
                Ui.Text("Si parte dalla sezione lorda. Dalle tensioni totali nella carpenteria si calcolano le larghezze efficaci dell’anima e degli sbalzi, poi si risolve nuovamente l’equilibrio. La parte semitrasparente con bordo arancio è esclusa dalla sezione resistente; non rappresenta la deformata dell’anima né un’instabilità a taglio.", 13),
                Ui.Text("Il modulo usa EN 1993-1-5:2006, §4.4 e tabelle 4.1–4.2 per pannelli senza irrigidimenti longitudinali. Gli sbalzi usano la tensione più compressiva nello spessore. Per ψ inferiore a −3, kσ e la curva di riduzione sono valutati a −3, conservando la larghezza compressa effettiva.", 13),
                Ui.Text("Rilassamento 0,55; tolleranza relativa 1E−7 sulle larghezze; massimo 120 iterazioni. Non convergenza o residuo normalizzato dell’equilibrio maggiore di 1E−5 impediscono un nuovo risultato valido. L’ultimo risultato visibile resta segnalato come «da aggiornare» e non può essere esportato come corrente.", 13)), true),
            Group("05 · Risultati, approssimazioni e librerie", Ui.Stack(
                Ui.Text("SLU, SLE rara e SLE quasi permanente selezionano i limiti tensionali: a parità degli altri dati cambiano i rapporti di verifica, non il campo elastico. Un CLS teso è segnalato; non si cerca automaticamente la porzione compressa della soletta.", 13),
                Ui.Text("Allo SLU gli incrementi N, Mx e V devono essere già combinati e coefficientati con γF e ψ: il modulo non li moltiplica nuovamente. I coefficienti γM0, γc e γs agiscono sulle resistenze. V è sommato per situazione e verificato sull’anima intera con EN 1993-1-5 §5. Gli irrigidimenti di appoggio usano un inviluppo di reazione R assegnato separatamente. I pioli usano q = Σ(V·S/I + Δq), seguendo le proprietà prescritte da NTC oppure EC4.", 13),
                Ui.Text("Le armature possono essere meno sollecitate dell’estradosso della trave perché non portano la fase iniziale di solo acciaio. Nelle fasi successive si confrontano i singoli contributi: le quote sono diverse e la tensione è E per la deformazione locale, con il modulo Es delle barre e Ea della carpenteria.", 13),
                Ui.Text("Le due piattabande inferiori sono disegnate separatamente. Nel calcolo si usa un rettangolo equivalente con area e spessore complessivi uguali: non conserva in generale baricentro e inerzia delle due piastre reali. Le proprietà di confronto restano disponibili nei risultati.", 13),
                Ui.Text("Model fornisce materiali, sezione da ponte, distribuzione delle barre e proprietà omogeneizzate. Checker risolve l’analisi lineare delle fasi composte. ANTHEA gestisce acciaio solo/soletta esclusa, somma dei contributi, riferimenti di N e iterazione delle larghezze efficaci.", 13),
                Ui.Text("Checker integra la carpenteria sulle linee medie delle pareti e le barre come aree concentrate. Per questo Ix geometrico completo e Ix di integrazione possono differire: sono entrambi esposti e l’audit dell’equilibrio usa le ipotesi di integrazione del solver.", 13),
                Notice(BridgeSection.Scope),
                Ui.Text("Sorgenti per la revisione: BridgeSection.Analysis.cs, BridgeSection.EffectiveWidths.cs e BridgeSection.Results.cs. Dipendenze, test e difetti ancora aperti sono descritti in supporto/docs/porting-checker-sezione-ponte.md; i bug numerici preesistenti non sono stati corretti da queste opzioni di vista.", 12)), true),
            Group("06 · Ritiro della soletta", Ui.Stack(
                Ui.Text("Ogni fase Ritiro assegna un incremento uniforme Δεcs al solo CLS: negativo per accorciamento, in µε (−250 µε = −0,25‰). Puoi inserire più fasi e spostarle nell’ordine desiderato. Ogni fase possiede φ, ψL e n; il valore iniziale di ψL è 0,55, modificabile.", 13),
                Ui.Text("Compatibilità: acciaio e barre seguono la deformazione della sezione. Il CLS reagisce alla differenza tra questa deformazione e il proprio ritiro libero: σc = Ec,eff · (ε − Δεcs). La contrazione della soletta genera quindi tensioni anche senza forze esterne.", 13),
                Ui.Text("Calcolo: si risolve Neq = Ec,eff · Ac,netto · Δεcs applicato al baricentro del CLS netto; poi si aggiunge −Ec,eff · Δεcs soltanto alle tensioni del CLS. Applicare soltanto Neq e Meq senza questa correzione darebbe un risultato errato. Le azioni equivalenti sono mostrate separatamente: la fase ha N, Mx e V esterni nulli.", 13),
                Notice("Sono inclusi gli effetti primari autoequilibrati sulla sezione. Eventuali effetti secondari da vincoli esterni vanno inseriti come azioni in una fase separata. Il modulo non calcola automaticamente ritiro da età/umidità né redistribuzione viscosa tra date.")), true));
        content.Children.Add(Group("07 · Taglio irrigidimenti e pioli", Ui.Stack(
            Ui.Text("VRd = min(Vpl,Rd; Vbw,Rd). Instabilità a taglio dell’anima: kτ, λw e χw sono esposti nella scheda Verifiche. Le zone semitrasparenti della viewport sono inefficaci per tensioni normali, non sono una rappresentazione del modo di instabilità a taglio.", 13),
            Ui.Text("Gli irrigidimenti possono essere mono o bilaterali, simmetrici o diversi, con pannelli adiacenti distinti. Si richiede vincolo laterale alle flange. Baricentro ed eccentricità sono calcolati dalla geometria reale. Si verificano inerzia, instabilità flessionale, torsione, freccia e tensione del II ordine. Se non idonei, il calcolo non attribuisce alcun incremento della resistenza a taglio.", 13),
            Ui.Text("Pioli: NTC §4.3.4.3.3 usa le proprietà della fase tensionale; EN 1994-2 §6.6.2.1 usa il CLS non fessurato anche per una fase con soletta esclusa. In questo caso φ/n servono al solo scorrimento. Il contributo G1 del solo acciaio è nullo. Il ritiro uniforme non determina lo scorrimento alle estremità: inserire Δq da un’analisi longitudinale.", 13),
            Ui.Text("Appoggio interno e terminale sono distinti dagli intermedi. R non è ricavata dal taglio della sezione. Un terminale rigido richiede due coppie bilaterali simmetriche distanziate di e e tutti i controlli previsti; altrimenti si mantiene la curva non rigida. Le saldature sono continue, senza intagli.", 13),
            Ui.Text("Le armature trasversali della soletta sono ingressi distinti dalle file longitudinali. Per la fatica si assegnano qmin, qmax, λv, φfat e, se la flangia va in trazione, ΔσE,2. Sono inviluppi dal modello globale, indipendenti dalla sequenza di fasi. I controlli mancanti sono sempre indicati come da verificare.", 13),
            Notice("Interazione M–V con capacità plastiche di riferimento per N=0, fy≤355 MPa e anima non tutta compressa. Negli altri casi, ad alto taglio, si applica un inviluppo elastico cautelativo senza riserva delle flange: ηnorm+(2ηV−1)²≤1. I controlli opzionali comprendono soletta a–a/b–b, ancoraggi, splitting al bordo e fatica pioli/flangia. Sollevamento e splitting nello spessore richiedono un modello dedicato. La colorazione σ/limite riguarda soltanto le tensioni normali.")), true));
        var dialog = Ui.Dialog(this, "Sezione composta · informazioni sul modello", new Border(), 1020, 800);
        dialog.Content = Ui.Paper(Ui.Dock(Scroll(content), bottom: Ui.Bar(Ui.Button("Chiudi", dialog.Close))), 18);
        dialog.ShowDialog();
    }
}
